server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui: /swagger-ui.html


